// This file is meant to be generated by the build.sh script
// This shell will be checked into git, but the actual build will generate a version of this file when it's built
package main

const buildVersion = -1
const gitSHA = "invalidSHA"
