version: '3'
services:
  webdriver:
    image: selenium/standalone-chrome:3.0
    logging:
        driver: "none"
    volumes:
      - /dev/shm:/dev/shm
  tests:
    build: "../build"
    ports:
        - "8080"
    links:
      - webdriver
    volumes:
      - ../..:/in:ro
    environment:
      LLTEST: 'true'
      LLDATABASE: 'sqlite'
      LLPORT: 8080
      LLHOST: "tests"
      LLWEBDRIVERURL: "http://webdriver:4444/wd/hub"
      LLDEBUGONERR: "true"
      GOPATH: /go
      LLBROWSER: 'chrome'
    command: 
      - /bin/sh
      - -c
      - |
        mkdir -p /go/src/github.com/lexLibrary/
        cp /in /go/src/github.com/lexLibrary/lexLibrary -R
        cd /go/src/github.com/lexLibrary/lexLibrary/ 
        ./build.sh
        go test ./web
