version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: lexlibrary
  tests:
    build: "../build"
    links:
      - postgres
    volumes:
      - ../..:/in:ro
    environment:
      LLDATABASE: 'postgres'
      LLTEST: 'true'
      GOPATH: /go
    command: 
      - /bin/sh
      - -c
      - |
        mkdir -p /go/src/github.com/lexLibrary/
        cp /in /go/src/github.com/lexLibrary/lexLibrary -R
        cd /go/src/github.com/lexLibrary/lexLibrary/ci
        sh ./test.sh
