version: '3'
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_PASSWORD: lexlibrary
  webdriver:
    image: selenium/standalone-firefox:3.11
    logging:
        driver: "none"
    volumes:
      - /dev/shm:/dev/shm
  tests:
    build: "../build"
    links:
      - postgres
      - webdriver
    volumes:
      - ../..:/in:ro
    environment:
      LLDATABASE: 'postgres'
      LLTEST: 'true'
      GOPATH: /go
      LLPORT: 8080
      LLHOST: "tests"
      LLWEBDRIVERURL: "http://webdriver:4444/wd/hub"
      LLBROWSER: 'firefox'
    command: 
      - /bin/sh
      - -c
      - |
        mkdir -p /go/src/github.com/lexLibrary/
        cp /in /go/src/github.com/lexLibrary/lexLibrary -R
        cd /go/src/github.com/lexLibrary/lexLibrary/ci
        sh ./test.sh
