version: '3'
services:
  webdriver:
    image: selenium/standalone-firefox:3.11
    logging:
        driver: "none"
    volumes:
      - /dev/shm:/dev/shm
  tests:
    build: "../build"
    links:
      - webdriver
    volumes:
      - ../..:/go/src/github.com/lexLibrary/lexLibrary
    environment:
      LLTEST: 'true'
      LLDATABASE: 'sqlite'
      LLPORT: 8080
      LLHOST: "tests"
      LLWEBDRIVERURL: "http://webdriver:4444/wd/hub"
      GOPATH: /go
      LLBROWSER: 'firefox'
    command: 
      - /bin/sh
      - -c
      - |
            cd /go/src/github.com/lexLibrary/lexLibrary/ 
            go test ./data -coverprofile=data.cover 
            go tool cover -html=data.cover -o data.html
            go test ./app -coverprofile=app.cover
            go tool cover -html=app.cover -o app.html
            go test ./web -coverprofile=web.cover
            go tool cover -html=web.cover -o web.html
