version: '3'
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: lexlibrary
  tests:
    build: "../build"
    links:
      - mysql
    volumes:
      - ../..:/in:ro
    environment:
      LLDATABASE: 'mysql'
      LLTEST: 'true'
      GOPATH: /go
    command: 
      - /bin/sh
      - -c
      - |
        mkdir -p /go/src/github.com/lexLibrary/
        cp /in /go/src/github.com/lexLibrary/lexLibrary -R
        cd /go/src/github.com/lexLibrary/lexLibrary/ci
        sh ./test.sh
