version: '3'
services:
  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: lexlibrary
  tests:
    build: "../build"
    links:
      - mariadb
    volumes:
      - ../..:/go/src/github.com/lexLibrary/lexLibrary
    environment:
      LLDATABASE: 'mariadb'
      LLTEST: 'true'
      GOPATH: /go
    command: sh -c '
        cd /go/src/github.com/lexLibrary/lexLibrary/ci/ && sh ./test.sh
      '
