Web:
  Port: 8080
  ReadTimeout: 60s
  WriteTimeout: 60s
  MaxUploadMemoryMB: 10
Data:
  DatabaseType: cockroachdb
  DatabaseUrl: "postgres://postgres/?user=postgres&password=lexlibrary&sslmode=disable"