version: '3'
services:
  cockroachdb:
    image: cockroachdb/cockroach:v2.1.0
    command: start --insecure
  tests:
    build: "../build"
    links:
      - cockroachdb
    volumes:
      - ../..:/in:ro
    environment:
      LLDATABASE: 'cockroachdb'
      LLTEST: 'true'
      GOPATH: /go
    command: 
      - /bin/sh
      - -c
      - |
        mkdir -p /go/src/github.com/lexLibrary/
        cp /in /go/src/github.com/lexLibrary/lexLibrary -R
        cd /go/src/github.com/lexLibrary/lexLibrary/ci
        sh ./test.sh
