version: '3'
services:
  cockroachdb:
    image: cockroachdb/cockroach:latest
    command: start --insecure
  tests:
    build: "../build"
    links:
      - cockroachdb
    volumes:
      - ../..:/go/src/github.com/lexLibrary/lexLibrary
    environment:
      LLDATABASE: 'cockroachdb'
      LLTEST: 'true'
      GOPATH: /go
    command: sh -c '
        cd /go/src/github.com/lexLibrary/lexLibrary/ci/ && sh ./test.sh
      '
