version: '3'
services:
  tests:
    build: "../build"
    volumes:
      - ../..:/go/src/github.com/lexLibrary/lexLibrary
    environment:
      LLDATABASE: 'sqlite'
      LLTEST: 'true'
      GOPATH: /go
    command: sh -c '
        cd /go/src/github.com/lexLibrary/lexLibrary/ci/ && sh ./test.sh
      '
