version: '3'
services:
  tests:
    build: "../build"
    volumes:
      - ../..:/in:ro
    environment:
      LLDATABASE: 'sqlite'
      LLTEST: 'true'
      GOPATH: /go
    command: 
      - /bin/sh
      - -c
      - |
        mkdir -p /go/src/github.com/lexLibrary/
        cp /in /go/src/github.com/lexLibrary/lexLibrary -R
        cd /go/src/github.com/lexLibrary/lexLibrary/ci
        sh ./test.sh
