version: '3'
services:
  webdriver:
    image: selenium/standalone-chrome
    volumes:
      - /dev/shm:/dev/shm
  tests:
    build: "../build"
    ports: 
        - "8070:8070"
    links:
      - webdriver
    volumes:
      - ../..:/go/src/github.com/lexLibrary/lexLibrary
    environment:
      LLTEST: 'true'
      LLDATABASE: 'sqlite'
      LLPORT: 8070
      LLHOST: "tests"
      LLWEBDRIVERURL: "http://webdriver:4444/wd/hub"
      GOPATH: /go
      LLBROWSER: 'chrome'
    command: sh -c '
        cd /go/src/github.com/lexLibrary/lexLibrary/ci/ && cd .. && ./build.sh && go test ./... -cover && go test ./... -race
      '
