version: '3'
services:
  tidb:
    image: pingcap/tidb:latest
  tests:
    build: "../build"
    links:
      - tidb
    volumes:
      - ../..:/go/src/github.com/lexLibrary/lexLibrary
    environment:
      LLDATABASE: 'tidb'
      LLTEST: 'true'
      GOPATH: /go
    command: sh -c '
        cd /go/src/github.com/lexLibrary/lexLibrary/ci/ && sh ./test.sh
      '
