version: '3'
services:
  sqlserver:
    image: microsoft/mssql-server-linux:2017-latest
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: lexlibraryP!ssw0rd
      MSSQL_PID: Express
  tests:
    build: "../build"
    links:
      - sqlserver
    volumes:
      - ../..:/in:ro
    environment:
      LLDATABASE: 'sqlserver'
      LLTEST: 'true'
      GOPATH: /go
    command: 
      - /bin/sh
      - -c
      - |
        mkdir -p /go/src/github.com/lexLibrary/
        cp /in /go/src/github.com/lexLibrary/lexLibrary -R
        cd /go/src/github.com/lexLibrary/lexLibrary/ci
        sh ./test.sh
