version: '3'
services:
  sqlserver:
    image: microsoft/mssql-server-linux
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: lexlibraryP!ssw0rd
      MSSQL_PID: Express
  webdriver:
    image: selenium/standalone-firefox:3.11
    logging:
        driver: "none"
    volumes:
      - /dev/shm:/dev/shm
  tests:
    build: "../build"
    links:
      - sqlserver
      - webdriver
    volumes:
      - ../..:/in
    environment:
      LLDATABASE: 'sqlserver'
      LLTEST: 'true'
      GOPATH: /go
      LLPORT: 8080
      LLHOST: "tests"
      LLWEBDRIVERURL: "http://webdriver:4444/wd/hub"
      LLBROWSER: 'firefox'
    command: 
      - /bin/sh
      - -c
      - |
        mkdir -p /go/src/github.com/lexLibrary/
        cp /in /go/src/github.com/lexLibrary/lexLibrary -R
        cd /go/src/github.com/lexLibrary/lexLibrary/ci
        sh ./test.sh
